# Generated by Django 6.0.6 on 2026-06-21 08:34

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SesiPenilaian',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mapel', models.CharField(max_length=50)),
                ('jenis', models.CharField(choices=[('formatif', 'Formatif'), ('sumatif', 'Sumatif')], max_length=10)),
                ('topik', models.CharField(max_length=100)),
                ('tanggal', models.DateField(default=datetime.date.today)),
                ('kelas', models.CharField(max_length=10)),
                ('guru', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-tanggal'],
            },
        ),
        migrations.CreateModel(
            name='Nilai',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skor', models.DecimalField(decimal_places=1, max_digits=5)),
                ('catatan', models.TextField(blank=True)),
                ('siswa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nilai', to='accounts.siswa')),
                ('sesi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='penilaian.sesipenilaian')),
            ],
            options={
                'unique_together': {('sesi', 'siswa')},
            },
        ),
    ]
