# Generated by Django 6.0.6 on 2026-09-11 00:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Percakapan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dibuat_pada', models.DateTimeField(auto_now_add=True)),
                ('diperbarui_pada', models.DateTimeField(auto_now=True)),
                ('peserta_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='percakapan_sebagai_1', to=settings.AUTH_USER_MODEL)),
                ('peserta_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='percakapan_sebagai_2', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-diperbarui_pada'],
                'unique_together': {('peserta_1', 'peserta_2')},
            },
        ),
        migrations.CreateModel(
            name='PesanPribadi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isi', models.TextField()),
                ('dikirim_pada', models.DateTimeField(auto_now_add=True)),
                ('sudah_dibaca', models.BooleanField(default=False)),
                ('pengirim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pesan_terkirim', to=settings.AUTH_USER_MODEL)),
                ('percakapan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pesan', to='pesan.percakapan')),
            ],
            options={
                'ordering': ['dikirim_pada'],
            },
        ),
    ]
