# Generated by Django 6.0.6 on 2026-06-22 00:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RuangKerja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mapel', models.CharField(max_length=50)),
                ('kelas', models.CharField(max_length=10)),
                ('deskripsi', models.TextField(blank=True)),
                ('dibuat_pada', models.DateTimeField(auto_now_add=True)),
                ('guru', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ruang_kerja_dikelola', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['kelas', 'mapel'],
                'unique_together': {('mapel', 'kelas')},
            },
        ),
        migrations.CreateModel(
            name='Pengumuman',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isi', models.TextField()),
                ('dibuat_pada', models.DateTimeField(auto_now_add=True)),
                ('diposting_oleh', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('ruang_kerja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pengumuman', to='ruang_kerja.ruangkerja')),
            ],
            options={
                'ordering': ['-dibuat_pada'],
            },
        ),
        migrations.CreateModel(
            name='Materi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=150)),
                ('deskripsi', models.TextField(blank=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='materi/')),
                ('dibuat_pada', models.DateTimeField(auto_now_add=True)),
                ('diunggah_oleh', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('ruang_kerja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materi', to='ruang_kerja.ruangkerja')),
            ],
            options={
                'ordering': ['-dibuat_pada'],
            },
        ),
    ]
