# Generated by Django 6.0.6 on 2026-06-22 08:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_siswa_user_alter_user_role'),
        ('ruang_kerja', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tugas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=150)),
                ('instruksi', models.TextField()),
                ('deadline', models.DateTimeField(blank=True, null=True)),
                ('nilai_maksimal', models.PositiveIntegerField(default=100)),
                ('dibuat_pada', models.DateTimeField(auto_now_add=True)),
                ('dibuat_oleh', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('ruang_kerja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tugas', to='ruang_kerja.ruangkerja')),
            ],
            options={
                'ordering': ['-dibuat_pada'],
            },
        ),
        migrations.CreateModel(
            name='SubmisiTugas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teks_jawaban', models.TextField(blank=True)),
                ('file_jawaban', models.FileField(blank=True, null=True, upload_to='submisi/')),
                ('dikirim_pada', models.DateTimeField(auto_now_add=True)),
                ('nilai', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('feedback', models.TextField(blank=True)),
                ('dinilai_pada', models.DateTimeField(blank=True, null=True)),
                ('siswa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submisi_tugas', to='accounts.siswa')),
                ('tugas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submisi', to='ruang_kerja.tugas')),
            ],
            options={
                'ordering': ['-dikirim_pada'],
                'unique_together': {('tugas', 'siswa')},
            },
        ),
    ]
