# Generated by Django 6.0.6 on 2026-06-22 23:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ruang_kerja', '0002_tugas_submisitugas'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Diskusi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=200)),
                ('isi', models.TextField()),
                ('dibuat_pada', models.DateTimeField(auto_now_add=True)),
                ('ditutup', models.BooleanField(default=False)),
                ('diposting_oleh', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('ruang_kerja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diskusi', to='ruang_kerja.ruangkerja')),
            ],
            options={
                'ordering': ['-dibuat_pada'],
            },
        ),
        migrations.CreateModel(
            name='KomentarDiskusi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isi', models.TextField()),
                ('dibuat_pada', models.DateTimeField(auto_now_add=True)),
                ('diposting_oleh', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('diskusi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='komentar', to='ruang_kerja.diskusi')),
            ],
            options={
                'ordering': ['dibuat_pada'],
            },
        ),
    ]
