# Generated by Django 6.0.6 on 2026-06-24 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ruang_kerja', '0003_diskusi_komentardiskusi'),
    ]

    operations = [
        migrations.AddField(
            model_name='materi',
            name='link_url',
            field=models.URLField(blank=True, help_text='Link website/artikel', null=True),
        ),
        migrations.AddField(
            model_name='materi',
            name='video_url',
            field=models.CharField(blank=True, help_text='Link YouTube/Google Drive', max_length=300, null=True),
        ),
    ]
