# Generated by Django 6.0.6 on 2026-06-24 23:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ruang_kerja', '0004_materi_link_url_materi_video_url'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='materi',
            options={'ordering': ['urutan', '-dibuat_pada']},
        ),
        migrations.AddField(
            model_name='materi',
            name='urutan',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='SubMateri',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=150)),
                ('deskripsi', models.TextField(blank=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='sub_materi/')),
                ('link_url', models.URLField(blank=True, null=True)),
                ('video_url', models.CharField(blank=True, max_length=300, null=True)),
                ('urutan', models.PositiveIntegerField(default=0)),
                ('dibuat_pada', models.DateTimeField(auto_now_add=True)),
                ('materi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_materi', to='ruang_kerja.materi')),
            ],
            options={
                'ordering': ['urutan', 'dibuat_pada'],
            },
        ),
    ]
