# Generated by Django 6.0.6 on 2026-07-13 01:38

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ruang_kerja', '0006_pesanchat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materi',
            name='deskripsi',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True),
        ),
        migrations.AlterField(
            model_name='submateri',
            name='deskripsi',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True),
        ),
    ]
