# Generated by Django 6.0.6 on 2026-07-13 10:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ruang_kerja', '0007_alter_materi_deskripsi_alter_submateri_deskripsi'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StatusBaca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('terakhir_dibaca', models.DateTimeField(auto_now=True)),
                ('ruang_kerja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_baca', to='ruang_kerja.ruangkerja')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_baca_ruang_kerja', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('ruang_kerja', 'user')},
            },
        ),
    ]
