# Generated by Django 6.0.6 on 2026-09-10 00:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_siswa_user_alter_user_role'),
        ('ruang_kerja', '0008_statusbaca'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='materi',
            name='deskripsi',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='submateri',
            name='deskripsi',
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name='AnggotaRuangKerja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ditambahkan_pada', models.DateTimeField(auto_now_add=True)),
                ('ditambahkan_oleh', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='anggota_ditambahkan', to=settings.AUTH_USER_MODEL)),
                ('ruang_kerja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anggota', to='ruang_kerja.ruangkerja')),
                ('siswa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ruang_kerja_diikuti', to='accounts.siswa')),
            ],
            options={
                'ordering': ['siswa__nama'],
                'unique_together': {('ruang_kerja', 'siswa')},
            },
        ),
    ]
