# Generated by Django 6.0.6 on 2026-09-10 08:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_siswa_user_alter_user_role'),
        ('ruang_kerja', '0010_matapelajaran'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CatatanRapor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('catatan', models.TextField(blank=True)),
                ('diperbarui_pada', models.DateTimeField(auto_now=True)),
                ('diperbarui_oleh', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('ruang_kerja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='catatan_rapor', to='ruang_kerja.ruangkerja')),
                ('siswa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='catatan_rapor', to='accounts.siswa')),
            ],
            options={
                'unique_together': {('ruang_kerja', 'siswa')},
            },
        ),
    ]
