# Generated by Django 6.0.6 on 2026-09-11 18:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_siswa_user_alter_user_role'),
        ('ruang_kerja', '0011_catatanrapor'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PenilaianTopik',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jenis', models.CharField(choices=[('formatif', 'Formatif'), ('sumatif', 'Sumatif'), ('remedial', 'Remedial')], max_length=10)),
                ('nilai', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('catatan', models.TextField(blank=True)),
                ('diperbarui_pada', models.DateTimeField(auto_now=True)),
                ('dinilai_oleh', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('materi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='penilaian', to='ruang_kerja.materi')),
                ('siswa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='penilaian_topik', to='accounts.siswa')),
            ],
            options={
                'ordering': ['jenis'],
                'unique_together': {('materi', 'siswa', 'jenis')},
            },
        ),
        migrations.CreateModel(
            name='RefleksiTopik',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isi', models.TextField(blank=True)),
                ('diperbarui_pada', models.DateTimeField(auto_now=True)),
                ('materi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refleksi', to='ruang_kerja.materi')),
                ('siswa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refleksi_topik', to='accounts.siswa')),
            ],
            options={
                'unique_together': {('materi', 'siswa')},
            },
        ),
    ]
