# Generated by Django 6.0.6 on 2026-09-11 19:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ruang_kerja', '0012_penilaiantopik_refleksitopik'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='penilaiantopik',
            options={'ordering': ['jenis', 'dibuat_pada']},
        ),
        migrations.AlterUniqueTogether(
            name='penilaiantopik',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='penilaiantopik',
            name='dibuat_pada',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2026, 9, 11, 19, 52, 36, 387204, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
