# Generated by Django 6.0.6 on 2026-09-11 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ruang_kerja', '0013_alter_penilaiantopik_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ruangkerja',
            name='kelas',
            field=models.CharField(max_length=100),
        ),
    ]
