# Generated by Django 6.0.6 on 2026-09-15 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ruang_kerja', '0014_alter_ruangkerja_kelas'),
    ]

    operations = [
        migrations.AddField(
            model_name='tugas',
            name='lampiran',
            field=models.FileField(blank=True, null=True, upload_to='tugas_lampiran/'),
        ),
    ]
