# Generated by Django 6.0.6 on 2026-09-16 06:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_siswa_user_alter_user_role'),
        ('ruang_kerja', '0015_tugas_lampiran'),
    ]

    operations = [
        migrations.AddField(
            model_name='tugas',
            name='jenis',
            field=models.CharField(choices=[('esai', 'Esai / Upload File'), ('pilihan_ganda', 'Pilihan Ganda')], default='esai', max_length=20),
        ),
        migrations.CreateModel(
            name='SoalPG',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pertanyaan', models.TextField()),
                ('urutan', models.PositiveIntegerField(default=0)),
                ('tugas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='soal_pg', to='ruang_kerja.tugas')),
            ],
            options={
                'ordering': ['urutan'],
            },
        ),
        migrations.CreateModel(
            name='OpsiPG',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teks', models.CharField(max_length=255)),
                ('is_benar', models.BooleanField(default=False)),
                ('soal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opsi', to='ruang_kerja.soalpg')),
            ],
        ),
        migrations.CreateModel(
            name='JawabanPG',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dijawab_pada', models.DateTimeField(auto_now=True)),
                ('siswa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jawaban_pg', to='accounts.siswa')),
                ('opsi_dipilih', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ruang_kerja.opsipg')),
                ('soal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jawaban', to='ruang_kerja.soalpg')),
            ],
            options={
                'unique_together': {('soal', 'siswa')},
            },
        ),
    ]
