# Generated by Django 6.0.6 on 2026-09-16 23:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ruang_kerja', '0016_tugas_jenis_soalpg_opsipg_jawabanpg'),
    ]

    operations = [
        migrations.CreateModel(
            name='MateriPrasyarat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mastery_required', models.PositiveSmallIntegerField(default=75, help_text='Persentase mastery minimal (0-100) dari topik prasyarat')),
                ('dibuat_pada', models.DateTimeField(auto_now_add=True)),
                ('materi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prasyarat', to='ruang_kerja.materi')),
                ('prasyarat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membuka', to='ruang_kerja.materi')),
            ],
            options={
                'ordering': ['materi', 'prasyarat'],
                'unique_together': {('materi', 'prasyarat')},
            },
        ),
    ]
