# Generated by Django 6.0.6 on 2026-09-17 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ruang_kerja', '0017_materiprasyarat'),
    ]

    operations = [
        migrations.AddField(
            model_name='catatanrapor',
            name='catatan_disiplin',
            field=models.TextField(blank=True, help_text='Perkembangan disiplin & kebiasaan belajar siswa'),
        ),
        migrations.AddField(
            model_name='catatanrapor',
            name='catatan_fisik_motorik',
            field=models.TextField(blank=True, help_text='Perkembangan fisik & motorik siswa'),
        ),
    ]
