# Generated by Django 6.1.1 on 2026-09-20 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ruang_kerja', '0018_catatanrapor_catatan_disiplin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ruangkerja',
            name='jenjang',
            field=models.CharField(blank=True, choices=[('sd_awal', 'SD Kelas 1-3'), ('sd_akhir', 'SD Kelas 4-6'), ('smp', 'SMP / Sederajat'), ('sma', 'SMA / SMK / Sederajat')], help_text='Kosongkan agar dideteksi otomatis dari nama kelas', max_length=10),
        ),
        migrations.AlterField(
            model_name='tugas',
            name='jenis',
            field=models.CharField(choices=[('esai', 'Esai / Upload File'), ('pilihan_ganda', 'Pilihan Ganda'), ('kreasi', 'Tugas Kreasi (Portofolio)')], default='esai', max_length=20),
        ),
    ]
