# Generated by Django 6.0.6 on 2026-07-12 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PengaturanSekolah',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_institusi', models.CharField(default='Sekolah Digital', max_length=200)),
                ('sub_judul', models.CharField(blank=True, default='', max_length=200)),
                ('mode', models.CharField(choices=[('formal', 'Sekolah Formal'), ('homeschool', 'Homeschooling'), ('kursus_online', 'Kursus Online')], default='formal', max_length=20)),
            ],
            options={
                'verbose_name': 'Pengaturan Sekolah',
                'verbose_name_plural': 'Pengaturan Sekolah',
            },
        ),
    ]
