# Generated by Django 6.0.6 on 2026-09-17 04:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_siswa_user_alter_user_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='KaryaSiswa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=150)),
                ('deskripsi', models.TextField(blank=True)),
                ('file', models.FileField(upload_to='karya_siswa/')),
                ('dibagikan', models.BooleanField(default=False, help_text='Jika dicentang, siswa lain juga bisa melihat karya ini')),
                ('diunggah_pada', models.DateTimeField(auto_now_add=True)),
                ('siswa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='karya', to='accounts.siswa')),
            ],
            options={
                'verbose_name_plural': 'Karya Siswa',
                'ordering': ['-diunggah_pada'],
            },
        ),
    ]
