# Generated by Django 6.0.6 on 2026-09-18 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portofolio', '0002_karyasiswa_refleksi'),
    ]

    operations = [
        migrations.AddField(
            model_name='karyasiswa',
            name='video_url',
            field=models.CharField(blank=True, help_text='Link YouTube/Google Drive (opsional)', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='karyasiswa',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='karya_siswa/'),
        ),
    ]
