# Generated by Django 6.0.6 on 2026-06-21 23:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='siswa',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profil_siswa', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('guru', 'Guru'), ('kepsek', 'Kepala Sekolah'), ('admin', 'Admin'), ('siswa', 'Siswa')], default='guru', max_length=10),
        ),
    ]
