# Generated by Django 6.0.6 on 2026-09-17 05:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_siswa_user_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='anak',
            field=models.ForeignKey(blank=True, help_text='Diisi hanya untuk akun dengan role Orang Tua', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orang_tua_list', to='accounts.siswa'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('guru', 'Guru'), ('kepsek', 'Kepala Sekolah'), ('admin', 'Admin'), ('siswa', 'Siswa'), ('orangtua', 'Orang Tua')], default='guru', max_length=10),
        ),
    ]
