# Generated by Django 6.0.6 on 2026-09-19 06:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_anak_alter_user_role'),
        ('perpustakaan', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lencana',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('ikon', models.CharField(blank=True, max_length=10)),
                ('deskripsi', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['nama'],
            },
        ),
        migrations.CreateModel(
            name='SumberDigital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=200)),
                ('deskripsi', models.TextField(blank=True)),
                ('jenis', models.CharField(choices=[('TEKS', 'E-Book / Teks'), ('AUDIO', 'Audiobook'), ('VIDEO', 'Video')], default='TEKS', max_length=10)),
                ('cover', models.ImageField(blank=True, null=True, upload_to='perpustakaan_cover/')),
                ('file', models.FileField(blank=True, null=True, upload_to='perpustakaan_sumber/')),
                ('link_url', models.URLField(blank=True, help_text='Link video YouTube atau audio eksternal', null=True)),
                ('dibuat_pada', models.DateTimeField(auto_now_add=True)),
                ('diunggah_oleh', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('lencana_hadiah', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='perpustakaan.lencana')),
            ],
            options={
                'ordering': ['-dibuat_pada'],
            },
        ),
        migrations.CreateModel(
            name='RefleksiSiswa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jenis', models.CharField(choices=[('TEKS', 'Teks'), ('AUDIO', 'Rekaman Suara'), ('FOTO', 'Foto Karya')], default='TEKS', max_length=10)),
                ('teks', models.TextField(blank=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='perpustakaan_refleksi/')),
                ('dibuat_pada', models.DateTimeField(auto_now_add=True)),
                ('siswa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refleksi_perpustakaan', to='accounts.siswa')),
                ('sumber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refleksi_list', to='perpustakaan.sumberdigital')),
            ],
            options={
                'ordering': ['-dibuat_pada'],
            },
        ),
        migrations.CreateModel(
            name='Zona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('ikon', models.CharField(blank=True, help_text='Emoji, contoh: (tempel manual di sini)', max_length=10)),
                ('warna', models.CharField(default='#0B3D26', max_length=20)),
                ('deskripsi', models.TextField(blank=True)),
                ('urutan', models.PositiveIntegerField(default=0)),
                ('dibuat_pada', models.DateTimeField(auto_now_add=True)),
                ('dibuat_oleh', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['urutan', 'nama'],
            },
        ),
        migrations.AddField(
            model_name='sumberdigital',
            name='zona',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sumber_list', to='perpustakaan.zona'),
        ),
        migrations.CreateModel(
            name='LencanaDiperoleh',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diperoleh_pada', models.DateTimeField(auto_now_add=True)),
                ('lencana', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='perpustakaan.lencana')),
                ('siswa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lencana_list', to='accounts.siswa')),
                ('sumber', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='perpustakaan.sumberdigital')),
            ],
            options={
                'ordering': ['-diperoleh_pada'],
                'unique_together': {('siswa', 'lencana', 'sumber')},
            },
        ),
    ]
