# Generated by Django 6.0.6 on 2026-09-19 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perpustakaan', '0002_lencana_sumberdigital_refleksisiswa_zona_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sumberdigital',
            name='teks_baca',
            field=models.TextField(blank=True, default='', help_text='Teks yang dibacakan otomatis (audiobook)'),
        ),
    ]
