# Generated by Django 6.1.1 on 2026-09-20 00:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perpustakaan', '0003_sumberdigital_teks_baca'),
    ]

    operations = [
        migrations.CreateModel(
            name='HalamanSumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomor', models.PositiveIntegerField()),
                ('gambar', models.ImageField(upload_to='perpustakaan_halaman/')),
                ('teks', models.TextField(blank=True)),
                ('sumber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='halaman_list', to='perpustakaan.sumberdigital')),
            ],
            options={
                'ordering': ['nomor'],
                'unique_together': {('sumber', 'nomor')},
            },
        ),
    ]
