# Generated by Django 6.1.1 on 2026-09-20 11:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_anak_alter_user_role'),
        ('perpustakaan', '0004_halamansumber'),
    ]

    operations = [
        migrations.CreateModel(
            name='RiwayatBaca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selesai_pada', models.DateTimeField(auto_now=True)),
                ('siswa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='riwayat_baca', to='accounts.siswa')),
                ('sumber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='riwayat_baca', to='perpustakaan.sumberdigital')),
            ],
            options={
                'ordering': ['-selesai_pada'],
                'unique_together': {('siswa', 'sumber')},
            },
        ),
    ]
