# Generated by Django 6.1.1 on 2026-09-22 03:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_anak_alter_user_role'),
        ('perpustakaan', '0005_riwayatbaca'),
    ]

    operations = [
        migrations.AddField(
            model_name='sumberdigital',
            name='topik',
            field=models.CharField(blank=True, default='', help_text='Kata kunci minat, pisahkan dengan koma', max_length=200),
        ),
        migrations.AddField(
            model_name='sumberdigital',
            name='usia_maks',
            field=models.PositiveSmallIntegerField(default=0, help_text='Usia maksimal (0 = tanpa batas)'),
        ),
        migrations.AddField(
            model_name='sumberdigital',
            name='usia_min',
            field=models.PositiveSmallIntegerField(default=0, help_text='Usia minimal (0 = semua umur)'),
        ),
        migrations.CreateModel(
            name='Glosarium',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('istilah', models.CharField(max_length=100)),
                ('arti', models.TextField()),
                ('sumber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='glosarium_list', to='perpustakaan.sumberdigital')),
            ],
            options={
                'ordering': ['istilah'],
                'unique_together': {('sumber', 'istilah')},
            },
        ),
        migrations.CreateModel(
            name='ProgresBaca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('halaman_terakhir', models.PositiveIntegerField(default=1)),
                ('total_halaman', models.PositiveIntegerField(default=0)),
                ('selesai', models.BooleanField(default=False)),
                ('diperbarui_pada', models.DateTimeField(auto_now=True)),
                ('siswa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progres_baca', to='accounts.siswa')),
                ('sumber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progres_list', to='perpustakaan.sumberdigital')),
            ],
            options={
                'ordering': ['-diperbarui_pada'],
                'unique_together': {('siswa', 'sumber')},
            },
        ),
    ]
