# Generated by Django 6.1.1 on 2026-09-20 12:29

import django.core.validators
import django.db.models.deletion
import kreasi.models
import kreasi.storage
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ruang_kerja', '0019_ruangkerja_jenjang_alter_tugas_jenis'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DimensiPenilaian',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jenjang', models.CharField(choices=[('sd_awal', 'SD Kelas 1-3'), ('sd_akhir', 'SD Kelas 4-6'), ('smp', 'SMP / Sederajat'), ('sma', 'SMA / SMK / Sederajat')], max_length=10)),
                ('kode', models.SlugField(max_length=40)),
                ('nama', models.CharField(max_length=100)),
                ('urutan', models.PositiveSmallIntegerField(default=0)),
                ('aktif', models.BooleanField(default=True, help_text='Nonaktifkan, jangan hapus, agar skor lama tetap tersimpan')),
            ],
            options={
                'verbose_name': 'Dimensi penilaian',
                'verbose_name_plural': 'Dimensi penilaian',
                'ordering': ['jenjang', 'urutan', 'id'],
                'unique_together': {('jenjang', 'kode')},
            },
        ),
        migrations.CreateModel(
            name='LampiranKarya',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipe', models.CharField(choices=[('foto', 'Foto'), ('audio', 'Rekaman Suara'), ('video', 'Video'), ('dokumen', 'Dokumen'), ('link', 'Tautan')], max_length=10)),
                ('file', models.FileField(blank=True, null=True, storage=kreasi.storage.private_storage, upload_to=kreasi.models._path_lampiran)),
                ('nama_asli', models.CharField(blank=True, max_length=255)),
                ('url', models.URLField(blank=True, max_length=500)),
                ('keterangan', models.CharField(blank=True, max_length=200)),
                ('urutan', models.PositiveSmallIntegerField(default=0)),
                ('dibuat_pada', models.DateTimeField(auto_now_add=True)),
                ('submisi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lampiran_karya', to='ruang_kerja.submisitugas')),
            ],
            options={
                'verbose_name': 'Lampiran karya',
                'verbose_name_plural': 'Lampiran karya',
                'ordering': ['urutan', 'id'],
            },
        ),
        migrations.CreateModel(
            name='RefleksiKarya',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipe', models.CharField(choices=[('emoji_suara', 'Emoji + Rekaman Suara'), ('teks_terbimbing', 'Teks Terbimbing'), ('matriks', 'Matriks Evaluasi Diri'), ('metakognitif', 'Refleksi Metakognitif')], max_length=20)),
                ('emoji', models.CharField(blank=True, help_text='Kunci pilihan emoji, mis. "bangga"', max_length=20)),
                ('jawaban', models.JSONField(blank=True, default=dict, help_text='Jawaban terbimbing / matriks, kunci = kode pertanyaan')),
                ('audio', models.FileField(blank=True, null=True, storage=kreasi.storage.private_storage, upload_to=kreasi.models._path_refleksi)),
                ('transkrip', models.TextField(blank=True, help_text='Diisi otomatis oleh speech-to-text pada tahap lanjutan')),
                ('dibuat_pada', models.DateTimeField(auto_now_add=True)),
                ('diperbarui_pada', models.DateTimeField(auto_now=True)),
                ('submisi', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='refleksi_karya', to='ruang_kerja.submisitugas')),
            ],
            options={
                'verbose_name': 'Refleksi karya',
                'verbose_name_plural': 'Refleksi karya',
            },
        ),
        migrations.CreateModel(
            name='DeskriptorLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.PositiveSmallIntegerField(choices=[(1, '1 - Mulai Berkembang'), (2, '2 - Berkembang'), (3, '3 - Cakap'), (4, '4 - Sangat Baik')])),
                ('kalimat', models.TextField()),
                ('dimensi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deskriptor', to='kreasi.dimensipenilaian')),
            ],
            options={
                'verbose_name': 'Deskriptor level',
                'verbose_name_plural': 'Deskriptor level',
                'ordering': ['dimensi', 'level'],
                'unique_together': {('dimensi', 'level')},
            },
        ),
        migrations.CreateModel(
            name='SkorDimensi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)])),
                ('catatan', models.TextField(blank=True)),
                ('diperbarui_pada', models.DateTimeField(auto_now=True)),
                ('dimensi', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='skor', to='kreasi.dimensipenilaian')),
                ('dinilai_oleh', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('submisi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skor_dimensi', to='ruang_kerja.submisitugas')),
            ],
            options={
                'verbose_name': 'Skor dimensi',
                'verbose_name_plural': 'Skor dimensi',
                'ordering': ['submisi', 'dimensi__urutan'],
                'unique_together': {('submisi', 'dimensi')},
            },
        ),
    ]
